In [14]:
import pandas as pd

In [15]:
df = pd.read_csv("Iris.csv")

In [16]:
df

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species
0,1,5.1,3.5,1.4,0.2,Iris-setosa
1,2,4.9,3.0,1.4,0.2,Iris-setosa
2,3,4.7,3.2,1.3,0.2,Iris-setosa
3,4,4.6,3.1,1.5,0.2,Iris-setosa
4,5,5.0,3.6,1.4,0.2,Iris-setosa
...,...,...,...,...,...,...
145,146,6.7,3.0,5.2,2.3,Iris-virginica
146,147,6.3,2.5,5.0,1.9,Iris-virginica
147,148,6.5,3.0,5.2,2.0,Iris-virginica
148,149,6.2,3.4,5.4,2.3,Iris-virginica
149,150,5.9,3.0,5.1,1.8,Iris-virginica

In [17]:
df["Id"]

0        1
1        2
2        3
3        4
4        5
      ...
145    146
146    147
147    148
148    149
149    150
Name: Id, Length: 150, dtype: int64

In [18]:
df[["Id", "SepalLengthCm"]]

      Id  SepalLengthCm
0      1            5.1
1      2            4.9
2      3            4.7
3      4            4.6
4      5            5.0
..   ...            ...
145  146            6.7
146  147            6.3
147  148            6.5
148  149            6.2
149  150            5.9

[150 rows x 2 columns]

In [19]:
df.head()

   Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [20]:
df.tail()

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species
145,146,6.7,3.0,5.2,2.3,Iris-virginica
146,147,6.3,2.5,5.0,1.9,Iris-virginica
147,148,6.5,3.0,5.2,2.0,Iris-virginica
148,149,6.2,3.4,5.4,2.3,Iris-virginica
149,150,5.9,3.0,5.1,1.8,Iris-virginica

In [21]:
df.head(7)

   Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa
5   6            5.4           3.9            1.7           0.4  Iris-setosa
6   7            4.6           3.4            1.4           0.3  Iris-setosa

In [23]:
df.iloc[0:2, 0:4]

   Id  SepalLengthCm  SepalWidthCm  PetalLengthCm
0   1            5.1           3.5            1.4
1   2            4.9           3.0            1.4

In [24]:
df.isna()

        Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  Species
0    False          False         False          False         False    False
1    False          False         False          False         False    False
2    False          False         False          False         False    False
3    False          False         False          False         False    False
4    False          False         False          False         False    False
..     ...            ...           ...            ...           ...      ...
145  False          False         False          False         False    False
146  False          False         False          False         False    False
147  False          False         False          False         False    False
148  False          False         False          False         False    False
149  False          False         False          False         False    False

[150 rows x 6 columns]

In [25]:
df["Id"].isna().sum()

np.int64(0)

In [26]:
df.dropna()

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species
0,1,5.1,3.5,1.4,0.2,Iris-setosa
1,2,4.9,3.0,1.4,0.2,Iris-setosa
2,3,4.7,3.2,1.3,0.2,Iris-setosa
3,4,4.6,3.1,1.5,0.2,Iris-setosa
4,5,5.0,3.6,1.4,0.2,Iris-setosa
...,...,...,...,...,...,...
145,146,6.7,3.0,5.2,2.3,Iris-virginica
146,147,6.3,2.5,5.0,1.9,Iris-virginica
147,148,6.5,3.0,5.2,2.0,Iris-virginica
148,149,6.2,3.4,5.4,2.3,Iris-virginica
149,150,5.9,3.0,5.1,1.8,Iris-virginica

In [28]:
d = pd.DataFrame({
    "name": ["Ali", None]
})

In [29]:
d["name"].ffill()

0    Ali
1    Ali
Name: name, dtype: object

In [32]:
d.bfill()

   name
0   Ali
1  None

In [33]:
df["Id"].duplicated()

0      False
1      False
2      False
3      False
4      False
       ...
145    False
146    False
147    False
148    False
149    False
Name: Id, Length: 150, dtype: bool

In [57]:
d = pd.DataFrame({
    "name": ["Ali", "Ali", "Fahad"],
    "marks": [90, 90, 89]
})

In [44]:
d

  name  marks
0  Ali     90
1  Ali     89

In [46]:
d.duplicated(subset=["name"], axis=1)

TypeError: DataFrame.duplicated() got an unexpected keyword argument 'axis'

In [50]:
df.dtypes

Id                 int64
SepalLengthCm    float64
SepalWidthCm     float64
PetalLengthCm    float64
PetalWidthCm     float64
Species           object
dtype: object

In [52]:
df["Id"].dtypes

dtype('int64')

In [53]:
d

  name  marks
0  Ali     90
1  Ali     89

In [55]:
d

    name  marks
0    Ali     90
1  Fahad     89
2    Ali     90

In [58]:
d.duplicated()

0    False
1     True
2    False
dtype: bool

In [65]:
d.drop_duplicates().reset_index(names=["fahad", "sana"])

   fahad   name  marks
0      0    Ali     90
1      2  Fahad     89

In [64]:
d["name"].reset_index()

   index   name
0      0    Ali
1      1    Ali
2      2  Fahad

In [63]:
d

    name  marks
0    Ali     90
1    Ali     90
2  Fahad     89

In [67]:
print(df.columns)

Index(['Id', 'SepalLengthCm', 'SepalWidthCm', 'PetalLengthCm', 'PetalWidthCm',
       'Species'],
      dtype='object')

In [68]:
data = {
'Name': ['Alice', 'Bob', 'Charlie'],
'Math': [85, 78, 92],
'Science': [90, 82, 89],
'English': [88, 85, 94]
}
df = pd.DataFrame(data)

In [69]:
df

      Name  Math  Science  English
0    Alice    85       90       88
1      Bob    78       82       85
2  Charlie    92       89       94

In [84]:
melted = df.melt(id_vars=["Name"], value_vars=["Math", "Science", "English"], var_name="Subject", value_name="Marks")

In [85]:
melted

      Name  Subject  Marks
0    Alice     Math     85
1      Bob     Math     78
2  Charlie     Math     92
3    Alice  Science     90
4      Bob  Science     82
5  Charlie  Science     89
6    Alice  English     88
7      Bob  English     85
8  Charlie  English     94

In [88]:
melted.pivot(index="Name", columns="Subject", values="Marks")

Subject  English  Math  Science
Name
Alice         88    85       90
Bob           85    78       82
Charlie       94    92       89

In [82]:
d.columns
d.name = "haha"
d.columns

Index(['name', 'marks'], dtype='object')