In [2]:
import pandas as pd

In [12]:
employees = pd.DataFrame({
    "EmpID": [1, 2, 3],
    "Name": ["Alice", "Bob", "Charlie"],
    "DeptID": [10, 20, 50]
})

departments = pd.DataFrame({
    "DeptID": [10, 20, 40],
    "DeptName": ["HR", "Engineering", "Marketing"]
})

In [13]:
employees

   EmpID     Name  DeptID
0      1    Alice      10
1      2      Bob      20
2      3  Charlie      50

In [14]:
departments

   DeptID     DeptName
0      10           HR
1      20  Engineering
2      40    Marketing

In [15]:
pd.merge(employees, departments, on="DeptID", how="left")

   EmpID     Name  DeptID     DeptName
0      1    Alice      10           HR
1      2      Bob      20  Engineering
2      3  Charlie      50          NaN

In [16]:
employees.shape

(3, 3)

In [17]:
employees.columns

Index(['EmpID', 'Name', 'DeptID'], dtype='object')

In [18]:
employees.index

RangeIndex(start=0, stop=3, step=1)